/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewNewRouteImport } from './routes/_authenticated/interview.new'
import { Route as AuthenticatedInterviewInterviewIdIndexRouteImport } from './routes/_authenticated/interview.$interviewId.index'
import { Route as AuthenticatedInterviewInterviewIdRoadmapRouteImport } from './routes/_authenticated/interview.$interviewId.roadmap'
import { Route as AuthenticatedInterviewInterviewIdReportRouteImport } from './routes/_authenticated/interview.$interviewId.report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewNewRoute =
  AuthenticatedInterviewNewRouteImport.update({
    id: '/interview/new',
    path: '/interview/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewInterviewIdIndexRoute =
  AuthenticatedInterviewInterviewIdIndexRouteImport.update({
    id: '/interview/$interviewId/',
    path: '/interview/$interviewId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewInterviewIdRoadmapRoute =
  AuthenticatedInterviewInterviewIdRoadmapRouteImport.update({
    id: '/interview/$interviewId/roadmap',
    path: '/interview/$interviewId/roadmap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewInterviewIdReportRoute =
  AuthenticatedInterviewInterviewIdReportRouteImport.update({
    id: '/interview/$interviewId/report',
    path: '/interview/$interviewId/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/interview/new': typeof AuthenticatedInterviewNewRoute
  '/interview/$interviewId/report': typeof AuthenticatedInterviewInterviewIdReportRoute
  '/interview/$interviewId/roadmap': typeof AuthenticatedInterviewInterviewIdRoadmapRoute
  '/interview/$interviewId/': typeof AuthenticatedInterviewInterviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/interview/new': typeof AuthenticatedInterviewNewRoute
  '/interview/$interviewId/report': typeof AuthenticatedInterviewInterviewIdReportRoute
  '/interview/$interviewId/roadmap': typeof AuthenticatedInterviewInterviewIdRoadmapRoute
  '/interview/$interviewId': typeof AuthenticatedInterviewInterviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/interview/new': typeof AuthenticatedInterviewNewRoute
  '/_authenticated/interview/$interviewId/report': typeof AuthenticatedInterviewInterviewIdReportRoute
  '/_authenticated/interview/$interviewId/roadmap': typeof AuthenticatedInterviewInterviewIdRoadmapRoute
  '/_authenticated/interview/$interviewId/': typeof AuthenticatedInterviewInterviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/resume'
    | '/interview/new'
    | '/interview/$interviewId/report'
    | '/interview/$interviewId/roadmap'
    | '/interview/$interviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/resume'
    | '/interview/new'
    | '/interview/$interviewId/report'
    | '/interview/$interviewId/roadmap'
    | '/interview/$interviewId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/resume'
    | '/_authenticated/interview/new'
    | '/_authenticated/interview/$interviewId/report'
    | '/_authenticated/interview/$interviewId/roadmap'
    | '/_authenticated/interview/$interviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/new': {
      id: '/_authenticated/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof AuthenticatedInterviewNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$interviewId/': {
      id: '/_authenticated/interview/$interviewId/'
      path: '/interview/$interviewId'
      fullPath: '/interview/$interviewId/'
      preLoaderRoute: typeof AuthenticatedInterviewInterviewIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$interviewId/roadmap': {
      id: '/_authenticated/interview/$interviewId/roadmap'
      path: '/interview/$interviewId/roadmap'
      fullPath: '/interview/$interviewId/roadmap'
      preLoaderRoute: typeof AuthenticatedInterviewInterviewIdRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$interviewId/report': {
      id: '/_authenticated/interview/$interviewId/report'
      path: '/interview/$interviewId/report'
      fullPath: '/interview/$interviewId/report'
      preLoaderRoute: typeof AuthenticatedInterviewInterviewIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedInterviewNewRoute: typeof AuthenticatedInterviewNewRoute
  AuthenticatedInterviewInterviewIdReportRoute: typeof AuthenticatedInterviewInterviewIdReportRoute
  AuthenticatedInterviewInterviewIdRoadmapRoute: typeof AuthenticatedInterviewInterviewIdRoadmapRoute
  AuthenticatedInterviewInterviewIdIndexRoute: typeof AuthenticatedInterviewInterviewIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedInterviewNewRoute: AuthenticatedInterviewNewRoute,
  AuthenticatedInterviewInterviewIdReportRoute:
    AuthenticatedInterviewInterviewIdReportRoute,
  AuthenticatedInterviewInterviewIdRoadmapRoute:
    AuthenticatedInterviewInterviewIdRoadmapRoute,
  AuthenticatedInterviewInterviewIdIndexRoute:
    AuthenticatedInterviewInterviewIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
